/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.GUI;

import com.mycompany.sistemabarberia.JPACOntrollers.tipodescuentoJpaController;
import com.mycompany.sistemabarberia.JTextFieldLimit;
import com.mycompany.sistemabarberia.Validaciones;
import com.mycompany.sistemabarberia.tipodescuento;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.text.PlainDocument;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author Jonathan Laux
 */
public class nuevoTipoDescuento extends javax.swing.JFrame {
    
    tipodescuentoJpaController tipodescuentoDAO = new tipodescuentoJpaController();
    Validaciones validar = new Validaciones();
    List<tipodescuento> descuentosEnBd = tipodescuentoDAO.findtipodescuentoEntities();
   

    /**
     * Creates new form nuevoTipoDescuento
     */
    public nuevoTipoDescuento() {
        initComponents();
        List<tipodescuento> descuentosEnBd = tipodescuentoDAO.findtipodescuentoEntities();
        if (descuentosEnBd.size() > 0)
        {
            idTipoDescuento.setText("ID Tipo de Documento: " + Integer.toString(descuentosEnBd.get(descuentosEnBd.size()-1).getIdtipodescuento()+1));
        }else
        {
            idTipoDescuento.setText("ID Tipo de Documento: 1");
        }
       
        
    }
    
    public void Reiniciar()
    {
        List<tipodescuento> descuentosEnBd = tipodescuentoDAO.findtipodescuentoEntities();
        if (descuentosEnBd.isEmpty())
        {
            idTipoDescuento.setText("ID Tipo de Documento: 1");
        }else
        {
            idTipoDescuento.setText("ID Tipo de Documento: " + Integer.toString(descuentosEnBd.get(descuentosEnBd.size()-1).getIdtipodescuento()+1));
        } 
        
        tipoDescuento.setText("Nombre del Tipo de Descuento");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idTipoDescuento = new javax.swing.JTextField();
        tipoDescuento = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        formatoInvalido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NUEVO TIPO DESCUENTO");

        idTipoDescuento.setEditable(false);
        idTipoDescuento.setBackground(new java.awt.Color(30, 33, 34));
        idTipoDescuento.setForeground(new java.awt.Color(255, 255, 255));
        idTipoDescuento.setText("ID Tipo de Descuento");
        idTipoDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTipoDescuentoActionPerformed(evt);
            }
        });

        tipoDescuento.setBackground(new java.awt.Color(30, 33, 34));
        tipoDescuento.setForeground(new java.awt.Color(255, 255, 255));
        tipoDescuento.setText("Nombre del Tipo de Descuento");
        tipoDescuento.setToolTipText("Ingrese un tipo de descuento válido.");
        tipoDescuento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tipoDescuentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tipoDescuentoFocusLost(evt);
            }
        });
        tipoDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDescuentoActionPerformed(evt);
            }
        });
        tipoDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tipoDescuentoKeyTyped(evt);
            }
        });

        botonAceptar.setBackground(new java.awt.Color(189, 158, 76));
        botonAceptar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonAceptar.setText("ACEPTAR");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        formatoInvalido.setText("Formato no valido.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formatoInvalido)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tipoDescuento)
                        .addComponent(idTipoDescuento)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(idTipoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(formatoInvalido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(botonAceptar)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        List<tipodescuento> descuentosEnBd = tipodescuentoDAO.findtipodescuentoEntities();
        String txt = tipoDescuento.getText();
        tipodescuento tipoDescuentoNuevo = new tipodescuento();
        tipoDescuentoNuevo.setNomDescuento(tipoDescuento.getText());
        tipoDescuentoNuevo.setActivo(true);
        
       
        for(int i=0; i < descuentosEnBd.size();i++)
        {
            if(tipoDescuentoNuevo.getNomDescuento().equalsIgnoreCase(descuentosEnBd.get(i).getNomDescuento()))
            {
                Border border = BorderFactory.createLineBorder(Color.RED, 1);
                tipoDescuento.setBorder(border);
                formatoInvalido.setEnabled(false);
                formatoInvalido.setText("Ese tipo de descuento ya existe.");
                return;
            }
        }
        
        if(validar.validacionCadenaPalabras(txt)){
            try {
            tipodescuentoDAO.create(tipoDescuentoNuevo);
            JOptionPane.showMessageDialog(null,"Operacion Exitosa");
                    Reiniciar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"No se pudo guardar, excepcion: " + ex.getMessage());
        }
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    
    
    private void idTipoDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTipoDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTipoDescuentoActionPerformed
//a;adir validaciones botonaceptar
    private void tipoDescuentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tipoDescuentoFocusLost

        if(validar.validacionCadenaPalabras(tipoDescuento.getText()))
        {
            Border border = BorderFactory.createLineBorder(Color.GREEN, 1);
            tipoDescuento.setBorder(border);
            formatoInvalido.setEnabled(true);
            formatoInvalido.setText("Formato válido");

            
        }else
        {
            Border border = BorderFactory.createLineBorder(Color.RED, 1);
            tipoDescuento.setBorder(border);
            formatoInvalido.setEnabled(false);
            formatoInvalido.setText("Formato inválido");

        }
        for(int i=0; i < descuentosEnBd.size();i++)
        {
            if(tipoDescuento.getText().equalsIgnoreCase(descuentosEnBd.get(i).getNomDescuento()))
            {
                Border border = BorderFactory.createLineBorder(Color.RED, 1);
            tipoDescuento.setBorder(border);
            formatoInvalido.setEnabled(false);
            formatoInvalido.setText("Ese tipo de descuento ya existe.");
            }
        }
        
    }//GEN-LAST:event_tipoDescuentoFocusLost

    private void tipoDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoDescuentoActionPerformed

    private void tipoDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipoDescuentoKeyTyped
        // TODO add your handling code here:
        if ((tipoDescuento.getText() + evt.getKeyChar()).length() > 20) {
        evt.consume();
    }
    }//GEN-LAST:event_tipoDescuentoKeyTyped

    private void tipoDescuentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tipoDescuentoFocusGained
        // TODO add your handling code here:
        tipoDescuento.setText("");
    }//GEN-LAST:event_tipoDescuentoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevoTipoDescuento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevoTipoDescuento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevoTipoDescuento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevoTipoDescuento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevoTipoDescuento().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JLabel formatoInvalido;
    private javax.swing.JTextField idTipoDescuento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tipoDescuento;
    // End of variables declaration//GEN-END:variables
}
