/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.GUI;

import com.mycompany.sistemabarberia.JPACOntrollers.bonosempleadomensualJpaController;
import com.mycompany.sistemabarberia.JPACOntrollers.empleadoJpaController;
import com.mycompany.sistemabarberia.JPACOntrollers.tiposbonoJpaController;
import com.mycompany.sistemabarberia.JTextFieldLimit;
import com.mycompany.sistemabarberia.Validaciones;
import com.mycompany.sistemabarberia.bonosempleadomensual;
import com.mycompany.sistemabarberia.empleado;
import com.mycompany.sistemabarberia.tiposbono;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Kesil
 */
public class NuevoBono extends javax.swing.JFrame {

    private empleadoJpaController nombreEmpleado = new empleadoJpaController();
    private tiposbonoJpaController bonos = new tiposbonoJpaController();
    private List<empleado> empleadosBD = nombreEmpleado.findempleadoEntities();
    private bonosempleadomensualJpaController bonosEmp = new bonosempleadomensualJpaController();
    private java.util.Date dt = new java.util.Date();
    private java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
    
    private Validaciones validar = new Validaciones();
    private ImageIcon imagen;
    private Icon icono;
    Border redBorder = BorderFactory.createLineBorder(Color.RED, 1);
    Border greenBorder = BorderFactory.createLineBorder(Color.GREEN, 1);
    Border defaultBorder = new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true);

    /**
     * Creates new form nuevoestadofactura
     */
    public NuevoBono() {
        initComponents();
        this.setLocationRelativeTo(null);
        formatoInvalidoPeriodo.setText("");
        this.insertarImagen(this.logo, "src/main/resources/Imagenes/logoBarberia.png");
        this.insertarImagen(this.salir, "src/main/resources/Imagenes/x.png");
        obtenerEmpleados();
        obtenerTipoBono();
        formatoInvalidoCantidad.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tituloPantalla = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        formatoInvalidoPeriodo = new javax.swing.JLabel();
        periodo = new javax.swing.JTextField();
        idEmpleado = new javax.swing.JComboBox<>();
        cantidad = new javax.swing.JTextField();
        cbTipoBono = new javax.swing.JComboBox<>();
        formatoInvalidoCantidad = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 17, 17));
        jPanel1.setMaximumSize(new java.awt.Dimension(334, 279));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPantalla.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        tituloPantalla.setForeground(new java.awt.Color(255, 255, 255));
        tituloPantalla.setText("NUEVO BONO");
        jPanel1.add(tituloPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 513, -1, -1));

        jPanel2.setBackground(new java.awt.Color(55, 53, 53));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setMaximumSize(new java.awt.Dimension(421, 280));
        jPanel2.setMinimumSize(new java.awt.Dimension(421, 280));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(55, 53, 53));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel3.setMaximumSize(new java.awt.Dimension(358, 219));
        jPanel3.setMinimumSize(new java.awt.Dimension(358, 219));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formatoInvalidoPeriodo.setForeground(new java.awt.Color(255, 255, 255));
        formatoInvalidoPeriodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formatoInvalidoPeriodo.setText("Formato no valido.");
        jPanel3.add(formatoInvalidoPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 270, 10));

        periodo.setBackground(new java.awt.Color(30, 33, 34));
        periodo.setDocument(new JTextFieldLimit(6));
        periodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        periodo.setForeground(new java.awt.Color(255, 255, 255));
        periodo.setText("Periodo");
        periodo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        periodo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                periodoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                periodoFocusLost(evt);
            }
        });
        periodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodoActionPerformed(evt);
            }
        });
        periodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                periodoKeyTyped(evt);
            }
        });
        jPanel3.add(periodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 270, 42));

        idEmpleado.setBackground(new java.awt.Color(30, 33, 34));
        idEmpleado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empleado", "Todos los empleados" }));
        idEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEmpleadoActionPerformed(evt);
            }
        });
        jPanel3.add(idEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 270, 44));

        cantidad.setBackground(new java.awt.Color(30, 33, 34));
        cantidad.setDocument(new JTextFieldLimit(25));
        cantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cantidad.setForeground(new java.awt.Color(255, 255, 255));
        cantidad.setText("Cantidad");
        cantidad.setToolTipText("Ingrese un nuevo Estado de Factura.");
        cantidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cantidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cantidadFocusLost(evt);
            }
        });
        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadKeyTyped(evt);
            }
        });
        jPanel3.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 110, 42));

        cbTipoBono.setBackground(new java.awt.Color(30, 33, 34));
        cbTipoBono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbTipoBono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        cbTipoBono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoBonoActionPerformed(evt);
            }
        });
        jPanel3.add(cbTipoBono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 110, 40));

        formatoInvalidoCantidad.setForeground(new java.awt.Color(255, 255, 255));
        formatoInvalidoCantidad.setText("Formato no valido.");
        jPanel3.add(formatoInvalidoCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 110, 20));

        Cancelar.setBackground(new java.awt.Color(189, 158, 76));
        Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Cancelar.setText("CANCELAR");
        Cancelar.setRequestFocusEnabled(false);
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel3.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 110, 30));

        aceptar.setBackground(new java.awt.Color(189, 158, 76));
        aceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aceptar.setText("ACEPTAR");
        aceptar.setRequestFocusEnabled(false);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel3.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 110, 30));

        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("ID Empleado:");
        jPanel3.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo Bono:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Periodo:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 28, 460, 340));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 104, 520, 400));

        jPanel5.setBackground(new java.awt.Color(20, 17, 17));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        salir.setText("jLabel2");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 33, 28));

        logo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 92, 98));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //a;adir validaciones botonaceptar
    public void obtenerEmpleados() {
        List<empleado> listaEmpleados;
        listaEmpleados = nombreEmpleado.findempleadoEntities();
        for (int i = 0; i < listaEmpleados.size(); i++) {
            idEmpleado.addItem(listaEmpleados.get(i).toString());
        }
    }

    public void obtenerTipoBono() {
        List<tiposbono> listaBonos;
        listaBonos = bonos.findtiposbonoEntities();
        for (int i = 0; i < listaBonos.size(); i++) {
            cbTipoBono.addItem(listaBonos.get(i).toString());
        }
    }


    private void periodoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_periodoFocusLost
        Validaciones validar = new Validaciones();
        validacionPeriodo(periodo,formatoInvalidoPeriodo);
    }//GEN-LAST:event_periodoFocusLost

    private void periodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodoActionPerformed

    private void periodoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_periodoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_periodoKeyTyped

    private void periodoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_periodoFocusGained
        // TODO add your handling code here:
        periodo.selectAll();
    }//GEN-LAST:event_periodoFocusGained

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        Bono bono = new Bono();
        bono.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirMouseClicked

    private void cantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidadFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadFocusGained

    private void cantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cantidadFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadFocusLost

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadKeyTyped

    private void idEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEmpleadoActionPerformed

    }//GEN-LAST:event_idEmpleadoActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        idEmpleado.setSelectedIndex(0);
        periodo.setText("Periodo");
        cbTipoBono.setSelectedIndex(0);
        cantidad.setText("Cantidad");
        formatoInvalidoCantidad.setText("");
        formatoInvalidoPeriodo.setText("");
        periodo.setBorder(BorderFactory.createLineBorder(Color.black, 1));
        cantidad.setBorder(BorderFactory.createLineBorder(Color.black, 1));
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bono().setVisible(true);
            }
        });
        this.dispose();
        
    }//GEN-LAST:event_CancelarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
       List<empleado> empleadosActivos = new ArrayList();
        
        for(int i=0 ; i < empleadosBD.size();i++)
        {
            if(empleadosBD.get(i).isActivo())
            {
                empleadosActivos.add(empleadosBD.get(i));
            }
        }
        
       if(idEmpleado.getSelectedIndex() == 1)
       {
           if(periodo.getText().equals("") || cantidad.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos.",
                    "Campos Incompletos",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
           int contador = 0;
           for(empleado empleado:empleadosBD)
           {
               bonosempleadomensual bonosEmpleadoMensual = new bonosempleadomensual();
               bonosEmpleadoMensual.setIdEmpleado(empleado.getIdempleado());
               bonosEmpleadoMensual.setIDTipoBono(Character.getNumericValue(cbTipoBono.getSelectedItem().toString().charAt(0)));
               bonosEmpleadoMensual.setPeriodo(periodo.getText());
               bonosEmpleadoMensual.setValor(Double.parseDouble(cantidad.getText()));
               bonosEmpleadoMensual.setActivo(true);
               if(validarDecimal() && validacionPeriodo(periodo,formatoInvalidoPeriodo))
                {
                    try {
                        bonosEmp.create(bonosEmpleadoMensual);
                        contador++;
                    } catch (Exception ex) {
                        //empleado con error
                        contador = empleado.getIdempleado();
                    }
                }else
                {
                    JOptionPane.showMessageDialog(null,"Por favor corrige campos en rojo.","Datos Inválidos",JOptionPane.ERROR_MESSAGE);
                }
           }
           if(contador == empleadosActivos.size())
           {
             JOptionPane.showMessageDialog(null,"Operacion Exitosa.");  
           }else
           {
              JOptionPane.showMessageDialog(null,"Error al aplicar deducción al empleado con Id número " + contador); 
           }
           return;
           
       }
       
        if (idEmpleado.getSelectedIndex() == 0 || periodo.getText().isEmpty()
                || cbTipoBono.getSelectedIndex() == 0 || cantidad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los datos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            bonosempleadomensual bonos = new bonosempleadomensual();
            bonos.setIdEmpleado(Character.getNumericValue(idEmpleado.getSelectedItem().toString().charAt(0)));
            bonos.setPeriodo(periodo.getText());
            bonos.setIDTipoBono(Character.getNumericValue(cbTipoBono.getSelectedItem().toString().charAt(0)));
            bonos.setValor(Double.parseDouble(cantidad.getText()));
            try {
                bonosEmp.create(bonos);
                JOptionPane.showMessageDialog(null, "El registro se ha almacenado satisfactoriamente", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                
            }
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void cbTipoBonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoBonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoBonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoBono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoBono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoBono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoBono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoBono().setVisible(true);
            }
        });

    }

    private void insertarImagen(JLabel lbl, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(),
                        lbl.getHeight(),
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }
    
     private boolean validarDecimal()
     {
         if(!validar.validacionCampoNumerico(cantidad.getText()))
         {
             cantidad.setBorder(redBorder);
             formatoInvalidoCantidad.setVisible(true);
             formatoInvalidoCantidad.setText("Solo puedes ingresar numeros en este campo.");
             return false;
         }
         
         if(Double.parseDouble(cantidad.getText()) <= 0)
        {
            cantidad.setBorder(redBorder);
            formatoInvalidoCantidad.setText("La cantidad debe ser mayor a 0.");
            return false;
        }
        
        if(validar.validacionDecimal(cantidad.getText()))
        {
            cantidad.setBorder(greenBorder);
            formatoInvalidoCantidad.setText(" ");
            return true;
        }else
        {
            cantidad.setBorder(redBorder);
            formatoInvalidoCantidad.setText("El formato debe ser 000000.00");
            return false;
        }  
         
     
     }

    private boolean validacionPeriodo(javax.swing.JTextField jText, JLabel label)
     {
         Calendar calendar = new GregorianCalendar();
        calendar.setTime(dt);
        int mes = calendar.get(Calendar.MONTH) + 1;
        
         String mesCampo = Character.toString(jText.getText().charAt(4)) + jText.getText().charAt(5);
         
         if(Integer.parseInt(mesCampo) > mes)
         {
             jText.setBorder(redBorder);
             formatoInvalidoPeriodo.setText("El mes del periodo debe concordar con el mes actual.");
           return false; 
         }
         System.out.println(mes);
         if(!validar.validacionCampoNumerico(jText.getText()))
         {
             jText.setBorder(redBorder);
             label.setVisible(true);
             JOptionPane.showMessageDialog(null,"Solo puedes ingresar periodos en este campo.\nEl formato de un periodo es aaaaMM.",
                     "Periodo Inválido",
                     JOptionPane.ERROR_MESSAGE);
             return false;
         }
       if(validar.validacionPeriodo(jText.getText()))
       {
           jText.setBorder(greenBorder);
           return true;
       }else
       {
           jText.setBorder(redBorder);
           JOptionPane.showMessageDialog(null,"Por favor verifica que el año y el mes del periodo "
                   + "otorgado sean válidos","Periodo Inválido",JOptionPane.ERROR_MESSAGE);
           return false; 
       }  
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JComboBox<String> cbTipoBono;
    private javax.swing.JLabel formatoInvalidoCantidad;
    private javax.swing.JLabel formatoInvalidoPeriodo;
    private javax.swing.JComboBox<String> idEmpleado;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField periodo;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel tituloPantalla;
    // End of variables declaration//GEN-END:variables
}
