/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.GUI;

import com.mycompany.sistemabarberia.JPACOntrollers.usuariosJpaController;
import com.mycompany.sistemabarberia.JTextFieldLimit;
import com.mycompany.sistemabarberia.NewClass;
import com.mycompany.sistemabarberia.PantallaCargando;
import com.mycompany.sistemabarberia.UsuarioSingleton;
import com.mycompany.sistemabarberia.usuarios;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.FileHandler;
import java.util.logging.SimpleFormatter;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author Jonathan Laux
 */
public class PantallaLogin extends javax.swing.JFrame {

    /**
     * Creates new form PantallaLogin
     */
    private EntityManagerFactory emf = Persistence.createEntityManagerFactory("servidorbd");

    private usuariosJpaController usuariosDAO = new usuariosJpaController(emf);
    private ImageIcon imagen;
    private Icon icono;
    PantallaCargando screen;
    private List<usuarios> usuariosBD = usuariosDAO.findusuariosEntities();



    public PantallaLogin() {
        //inicioPantalla();
        //screen.velocidadDeCarga();
        initComponents();
        this.setLocationRelativeTo(null);
        Image icon = new ImageIcon(getClass().getResource("/Imagenes/logoBarberia.jpeg")).getImage();
        setIconImage(icon);
        this.insertarImagen(this.logo,"/Imagenes/logoLogin.png");
        this.insertarImagen(this.imgLogin,"/Imagenes/loginImage.png");
        mostrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hide.png")));
        usuarioLbl.setText(" ");
    }

//     private  void inicioPantalla() {
//    ImageIcon myImage = new ImageIcon(getClass().getResource("/Imagenes/logoBarberia.png"));
//    screen = new PantallaCargando(myImage);
//    screen.setLocationRelativeTo(null);
//    screen.setProgresoMax(100);
//    screen.setVisible(true);
//  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        imgLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        iniciarSesion = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        mostrar = new javax.swing.JToggleButton();
        exit = new javax.swing.JButton();
        usuarioLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(20, 17, 17));

        logo.setForeground(new java.awt.Color(255, 255, 255));

        imgLogin.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENIDO");

        nombreUsuario.setBackground(new java.awt.Color(30, 33, 34));
        nombreUsuario.setDocument(new JTextFieldLimit(17));
        nombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        nombreUsuario.setText("Nombre de Usuario");
        nombreUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        nombreUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreUsuarioFocusLost(evt);
            }
        });

        iniciarSesion.setBackground(new java.awt.Color(189, 158, 76));
        iniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        iniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.png"))); // NOI18N
        iniciarSesion.setText("Iniciar Sesion");
        iniciarSesion.setRequestFocusEnabled(false);
        iniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarSesionMouseClicked(evt);
            }
        });
        iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionActionPerformed(evt);
            }
        });

        password.setBackground(new java.awt.Color(30, 33, 34));
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");

        mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/show.png"))); // NOI18N
        mostrar.setContentAreaFilled(false);
        mostrar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mostrarStateChanged(evt);
            }
        });
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        exit.setContentAreaFilled(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        usuarioLbl.setForeground(new java.awt.Color(255, 255, 255));
        usuarioLbl.setText("Nombre de Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addComponent(usuarioLbl)
                            .addComponent(iniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 39, Short.MAX_VALUE)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usuarioLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(iniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void iniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {

    }


    public usuarios encontrarUsuario(String nomUsuario){
        usuarios usuarioActual = new usuarios();
        for(int i = 0; i < usuariosBD.size(); i++)
        {
            if(nomUsuario.equals(usuariosBD.get(i).getNomCuenta()))
            {
                usuarioActual = usuariosBD.get(i);
                return usuarioActual;
            }
        }
        usuarioActual = null;
        return usuarioActual;
    }

    private void iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try{
        String contrasena = new String(password.getPassword());
        String contraEncriptada = DigestUtils.md5Hex(contrasena);
        usuarios usuarioActual = null;
        if(nombreUsuario.getText().equals("Nombre de Usuario") || contrasena.equals("") || nombreUsuario.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Ingresa un usuario y una contraseña","Credenciales vacías",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        usuarioActual = encontrarUsuario(nombreUsuario.getText());

        //verificar contrasena
        if(usuarioActual == null)
        {
            JOptionPane.showMessageDialog(null,"Contraseña o usuario incorrectos.", "Credenciales incorrectas", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(usuarioActual.getIntentos() == 3)
                {
                    JOptionPane.showMessageDialog(null,"Alguien intento acceder a tu cuenta sin éxito 3 veces, "
                            + "tu usuario ha sido bloqueado.","Usuario Bloqueado",JOptionPane.ERROR_MESSAGE);
                    return;
                }else
                {
                    if(!usuarioActual.getActivo())
                    {
                         JOptionPane.showMessageDialog(null,"Este usuario ha sido desactivado, "
                            + "comunicate con el gerente.","Usuario Desactivado",JOptionPane.ERROR_MESSAGE);
                    return;
                    }
                    if(contraEncriptada.equals(usuarioActual.getContrasena()))
                {
                    usuarioActual.setIdusuario(usuarioActual.getIdusuario());
                    usuarioActual.setIntentos(0);
                    usuarioActual.setIDEmpleado(usuarioActual.getIDEmpleado());
                    usuarioActual.setNomCuenta(usuarioActual.getNomCuenta());
                    usuarioActual.setContrasena(usuarioActual.getContrasena());
                    usuarioActual.setActivo(true);
                    UsuarioSingleton usuario= UsuarioSingleton.getUsuario(usuarioActual);
                    usuario.setUsuario(usuarioActual);
                    try{usuariosDAO.edit(usuarioActual);
                    }catch(Exception ex)
                    {}
                   java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                    new PantallaFactura().setVisible(true);
                        }
                    });
                   emf.close();
                    this.setVisible(false);
                    this.dispose();
                }else
                {
                    JOptionPane.showMessageDialog(null,"Contraseña o usuario incorrectos.", "Credenciales incorrectas", JOptionPane.ERROR_MESSAGE);
                    password.selectAll();
                    usuarioActual.setIdusuario(usuarioActual.getIdusuario());
                    usuarioActual.setIDEmpleado(usuarioActual.getIDEmpleado());
                    usuarioActual.setIntentos(usuarioActual.getIntentos()+1);
                    usuarioActual.setNomCuenta(usuarioActual.getNomCuenta());
                    usuarioActual.setContrasena(usuarioActual.getContrasena());
                    if(usuarioActual.getIntentos() == 3)
                    {
                        usuarioActual.setActivo(false);
                    }else
                    {
                      usuarioActual.setActivo(true);
                    }
                    try{
                        usuariosDAO.edit(usuarioActual);
                        return;
                    }catch(Exception ex)
                    {System.out.println(ex);}
                }
        }
        contrasena = "";
        }catch(Exception ex){
        log(ex);
        }
    }

    private void nombreUsuarioFocusGained(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        if(nombreUsuario.getText().equals("Nombre de Usuario"))
        {
            nombreUsuario.setText("");
            usuarioLbl.setText("Nombre de Usuario:");
        }
    }

    private void nombreUsuarioFocusLost(java.awt.event.FocusEvent evt) {
        // TODO add your handling code here:
        if(nombreUsuario.getText().equals(""))
        {
            nombreUsuario.setText("Nombre de Usuario");
            usuarioLbl.setText(" ");
        }
    }

    private void mostrarStateChanged(javax.swing.event.ChangeEvent evt) {
        // TODO add your handling code here:
        try{
        if(mostrar.isSelected())
        {
            password.setEchoChar((char)0);
        }else
        {
            password.setEchoChar('*');
        }
        }catch(Exception ex){
            log(ex);
        }
    }

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        emf.close();
        System.exit(0);
    }

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        iniciarSesionActionPerformed(evt);
    }

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       //NewClass carga = new NewClass();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaLogin().setVisible(true);
            }
        });
    }

     private void insertarImagen(JLabel lbl,String ruta)
    {
        this.imagen = new ImageIcon(getClass().getResource(ruta));
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(),
                        lbl.getHeight(),
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }

     public boolean validarCamposEnBlanco(){
         if(nombreUsuario.getText().equals("Nombre de Usuario") || password.equals("") || nombreUsuario.getText().equals(""))
        {
            return false;
        }else{return true;}
     }
     
     private void log(Exception ex){
        FileHandler fh;                              
            java.util.logging.Logger logger = java.util.logging.Logger.getLogger("Log");  
            try {
                Timestamp timestamp = new Timestamp(System.currentTimeMillis());
                String ts = new SimpleDateFormat("dd MMMM yyyy HH.mm.ss").format(timestamp);
                fh = new FileHandler("../logs/"+ ts + " " + this.getClass().getName()+".txt" );
                logger.addHandler(fh);
                SimpleFormatter formatter = new SimpleFormatter();
                fh.setFormatter(formatter);
                logger.info(ex.getClass().toString() + " : " +ex.getMessage());
            } catch (SecurityException e) {  
                e.printStackTrace();  
            } catch (IOException e) {  
                e.printStackTrace();  
            } 
    }

    // Variables declaration - do not modify
    private javax.swing.JButton exit;
    private javax.swing.JLabel imgLogin;
    private javax.swing.JButton iniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JToggleButton mostrar;
    public javax.swing.JTextField nombreUsuario;
    public javax.swing.JPasswordField password;
    private javax.swing.JLabel usuarioLbl;
    // End of variables declaration
}
