/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.GUI;

import com.mycompany.sistemabarberia.JPACOntrollers.parametrosJpaController;
import com.mycompany.sistemabarberia.parametros;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.sql.Date;

/**
 *
 * @author Kesil
 */
public class parametrosFactura extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;
    parametrosJpaController parametros = new parametrosJpaController();

    /**
     * Creates new form nuevoTipoDescuento
     */
    public parametrosFactura() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/main/resources/Imagenes/logoBarberia.jpeg"));
        this.insertarImagen(this.logo, "src/main/resources/Imagenes/logoBarberia.png");
        this.insertarImagen(this.salir1,"src/main/resources/Imagenes/x.png");
        txtIdParametro.setEditable(false);
        Reiniciar();
    }

    public void Reiniciar() 
    {
        List<parametros> parametrosBD = parametros.findparametrosEntities();
        if (parametrosBD.isEmpty())
        {
            txtIdParametro.setText("ID Parametro: 1");
        }else
        {
            txtIdParametro.setText("ID Parametro: " + Integer.toString(parametrosBD.get(parametrosBD.size()-1).getIdparametro()+1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloPantalla = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtFechaFinal = new javax.swing.JTextField();
        txtIdParametro = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtLlave = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        lbIdParametro = new javax.swing.JLabel();
        lbFechaInicio = new javax.swing.JLabel();
        lbFechaFinal = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        lbLlave = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        salir1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 17, 17));
        jPanel1.setMaximumSize(new java.awt.Dimension(334, 279));

        tituloPantalla.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        tituloPantalla.setForeground(new java.awt.Color(255, 255, 255));
        tituloPantalla.setText("PARAMETROS");

        logo.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(55, 53, 53));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setMaximumSize(new java.awt.Dimension(421, 280));
        jPanel2.setMinimumSize(new java.awt.Dimension(421, 280));

        jPanel3.setBackground(new java.awt.Color(55, 53, 53));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel3.setMaximumSize(new java.awt.Dimension(358, 219));
        jPanel3.setMinimumSize(new java.awt.Dimension(358, 219));

        txtFechaFinal.setBackground(new java.awt.Color(30, 33, 34));
        txtFechaFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFechaFinal.setForeground(new java.awt.Color(153, 153, 153));
        txtFechaFinal.setText("Fecha Final");
        txtFechaFinal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtFechaFinal.setSelectionColor(new java.awt.Color(55, 53, 53));
        txtFechaFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFechaFinalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFechaFinalFocusLost(evt);
            }
        });
        txtFechaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFinalActionPerformed(evt);
            }
        });

        txtIdParametro.setBackground(new java.awt.Color(30, 33, 34));
        txtIdParametro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIdParametro.setForeground(new java.awt.Color(153, 153, 153));
        txtIdParametro.setText("ID Parametro");
        txtIdParametro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtIdParametro.setSelectionColor(new java.awt.Color(55, 53, 53));
        txtIdParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdParametroActionPerformed(evt);
            }
        });

        txtValor.setBackground(new java.awt.Color(30, 33, 34));
        txtValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtValor.setForeground(new java.awt.Color(153, 153, 153));
        txtValor.setText("Valor");
        txtValor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtValor.setSelectionColor(new java.awt.Color(55, 53, 53));
        txtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorFocusLost(evt);
            }
        });
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        txtLlave.setBackground(new java.awt.Color(30, 33, 34));
        txtLlave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLlave.setForeground(new java.awt.Color(153, 153, 153));
        txtLlave.setText("Llave");
        txtLlave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtLlave.setSelectionColor(new java.awt.Color(55, 53, 53));
        txtLlave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLlaveFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLlaveFocusLost(evt);
            }
        });
        txtLlave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLlaveActionPerformed(evt);
            }
        });

        txtFechaInicio.setBackground(new java.awt.Color(30, 33, 34));
        txtFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtFechaInicio.setForeground(new java.awt.Color(153, 153, 153));
        txtFechaInicio.setText("Fecha de Inicio");
        txtFechaInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtFechaInicio.setSelectionColor(new java.awt.Color(55, 53, 53));
        txtFechaInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFechaInicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFechaInicioFocusLost(evt);
            }
        });
        txtFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInicioActionPerformed(evt);
            }
        });

        lbIdParametro.setForeground(new java.awt.Color(255, 255, 255));
        lbIdParametro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbFechaInicio.setForeground(new java.awt.Color(255, 255, 255));
        lbFechaInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbFechaFinal.setForeground(new java.awt.Color(255, 255, 255));
        lbFechaFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbValor.setForeground(new java.awt.Color(255, 255, 255));
        lbValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbLlave.setForeground(new java.awt.Color(255, 255, 255));
        lbLlave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaFinal)
                            .addComponent(txtValor)
                            .addComponent(txtLlave)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(txtIdParametro)
                            .addComponent(lbFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbFechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbIdParametro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbLlave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtIdParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lbIdParametro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lbFechaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lbFechaFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lbValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLlave, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLlave)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        botonGuardar.setBackground(new java.awt.Color(189, 158, 76));
        botonGuardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonGuardar.setText("GUARDAR");
        botonGuardar.setRequestFocusEnabled(false);
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarMouseClicked(evt);
            }
        });
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        salir1.setText("jLabel2");
        salir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salir1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(tituloPantalla))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                        .addComponent(salir1))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tituloPantalla))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public String convertirFecha(String Fecha){
        String[] palabras  = Fecha.split("/");
        return palabras[2] + "-" + palabras[1] + "-" + palabras[0];
    }
    
    public void limpiar(){
        txtFechaInicio.setText("Fecha de Inicio");
        txtFechaInicio.setForeground(new Color(153, 153, 153));
        txtFechaFinal.setText("Fecha Final");
        txtFechaFinal.setForeground(new Color(153, 153, 153));
        txtValor.setText("Valor");
        txtValor.setForeground(new Color(153, 153, 153));
        txtLlave.setText("Llave");
        txtLlave.setForeground(new Color(153, 153, 153));
        lbFechaInicio.setText("");
        lbFechaFinal.setText("");
        lbValor.setText("");
        lbLlave.setText("");
        txtFechaInicio.setBorder(BorderFactory.createLineBorder(Color.black, 1));
        txtFechaFinal.setBorder(BorderFactory.createLineBorder(Color.black, 1));
        txtValor.setBorder(BorderFactory.createLineBorder(Color.black, 1));
        txtLlave.setBorder(BorderFactory.createLineBorder(Color.black, 1));   
    }
    
    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if (txtFechaInicio.getText().isEmpty() || txtFechaFinal.getText().isEmpty() || txtValor.getText().isEmpty() || txtLlave.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Debes de llenar todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else if (!txtFechaInicio.getText().matches("^\\d{2}[/]{1}\\d{2}[/]{1}\\d{4}$")) {
            JOptionPane.showConfirmDialog(null, "Formato de fecha inicio inválido\nFormato correcto: dd/mm/yyyy", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!txtFechaFinal.getText().matches("^\\d{2}[/]{1}\\d{2}[/]{1}\\d{4}$")) {
            JOptionPane.showConfirmDialog(null, "Formato de fecha final inválido\nFormato correcto: dd/mm/yyyy", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!txtValor.getText().equals("CAI")) {
            JOptionPane.showConfirmDialog(null, "En este campo se debe escribir: CAI ", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!txtLlave.getText().matches("^[A-Z,0-9]{6}[-]{1}[A-Z,0-9]{6}[-]{1}[A-Z,0-9]{6}[-]{1}[A-Z,0-9]{6}[-]{1}[A-Z,0-9]{2}$")) {
            JOptionPane.showConfirmDialog(null, "El CAI debe contener 26 caracteres\nDeben ser numeros y letras\nFormato correcto: XXXXXX-XXXXXX-XXXXXX-XXXXXX-XX ", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            parametros pm = new parametros();

            pm.setFechaInicio(Date.valueOf(convertirFecha(txtFechaInicio.getText())));
            pm.setFechaFinal(Date.valueOf(convertirFecha(txtFechaFinal.getText())));
            pm.setValor(txtValor.getText());
            pm.setLlave(txtLlave.getText());
            pm.setActivo(true);
            try {
                parametros.create(pm);
                limpiar();
                JOptionPane.showConfirmDialog(null, "El registro se ha almacenado correctamente", "Notificación", JOptionPane.OK_OPTION);
            } catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
        this.setVisible(false);
    }//GEN-LAST:event_botonGuardarMouseClicked

    private void txtFechaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFinalActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtLlaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLlaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLlaveActionPerformed

    private void txtFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicioActionPerformed

    private void txtIdParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdParametroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdParametroActionPerformed

    private void txtFechaInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaInicioFocusGained
        if (txtFechaInicio.getText().equals("Fecha de Inicio")) {
            txtFechaInicio.setText("");
            txtFechaInicio.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_txtFechaInicioFocusGained

    private void txtFechaInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaInicioFocusLost
        if (txtFechaInicio.getText().equals("")) {
            txtFechaInicio.setText("Fecha de Inicio");
            txtFechaInicio.setForeground(new Color(153, 153, 153));
            txtFechaInicio.setBorder(BorderFactory.createLineBorder(Color.black, 1));
            lbFechaInicio.setText("");
        } else if (!txtFechaInicio.getText().matches("^\\d{2}[/]{1}\\d{2}[/]{1}\\d{4}$")) {
            txtFechaInicio.setBorder(BorderFactory.createLineBorder(Color.red, 1));
            lbFechaInicio.setText("Formato incorrecto: dd/mm/aaaa");
        } else {
            txtFechaInicio.setBorder(BorderFactory.createLineBorder(Color.green, 1));
            lbFechaInicio.setText("Formato correcto");
        }
    }//GEN-LAST:event_txtFechaInicioFocusLost

    private void txtFechaFinalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaFinalFocusGained
        if (txtFechaFinal.getText().equals("Fecha Final")) {
            txtFechaFinal.setText("");
            txtFechaFinal.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_txtFechaFinalFocusGained

    private void txtFechaFinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaFinalFocusLost
        if (txtFechaFinal.getText().equals("")) {
            txtFechaFinal.setText("Fecha Final");
            txtFechaFinal.setForeground(new Color(153, 153, 153));
            txtFechaFinal.setBorder(BorderFactory.createLineBorder(Color.black, 1));
            lbFechaFinal.setText("");
        } else if (!txtFechaFinal.getText().matches("^\\d{2}[/]{1}\\d{2}[/]{1}\\d{4}$")) {
            txtFechaFinal.setBorder(BorderFactory.createLineBorder(Color.red, 1));
            lbFechaFinal.setText("Formato incorrecto: dd/mm/aaaa");
        } else {
            txtFechaFinal.setBorder(BorderFactory.createLineBorder(Color.green, 1));
            lbFechaFinal.setText("Formato correcto");
        }
    }//GEN-LAST:event_txtFechaFinalFocusLost

    private void txtValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusGained
        if (txtValor.getText().equals("Valor")) {
            txtValor.setText("");
            txtValor.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_txtValorFocusGained

    private void txtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusLost
        if (txtValor.getText().equals("")) {
            txtValor.setText("Valor");
            txtValor.setForeground(new Color(153, 153, 153));
            txtValor.setBorder(BorderFactory.createLineBorder(Color.black, 1));
            lbValor.setText("");
        } else if (!txtValor.getText().equals("CAI")) {
            txtValor.setBorder(BorderFactory.createLineBorder(Color.red, 1));
            lbValor.setText("Debes escribir CAI");
        } else {
            txtValor.setBorder(BorderFactory.createLineBorder(Color.green, 1));
            lbValor.setText("Formato correcto");
        }
    }//GEN-LAST:event_txtValorFocusLost

    private void txtLlaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLlaveFocusGained
        if (txtLlave.getText().equals("Llave")) {
            txtLlave.setText("");
            txtLlave.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_txtLlaveFocusGained

    private void txtLlaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLlaveFocusLost
        if (txtLlave.getText().equals("")) {
            txtLlave.setText("Llave");
            txtLlave.setForeground(new Color(153, 153, 153));
            txtLlave.setBorder(BorderFactory.createLineBorder(Color.black, 1));
            lbLlave.setText("");
        } else if (!txtLlave.getText().matches("^[A-Z,0-9]{6}[-]{1}[A-Z,0-9]{6}[-]{1}[A-Z,0-9]{6}[-]{1}[A-Z,0-9]{6}[-]{1}[A-Z,0-9]{2}$")) {
            txtLlave.setBorder(BorderFactory.createLineBorder(Color.red, 1));
            lbLlave.setText("Formato incorrecto: XXXXXX-XXXXXX-XXXXXX-XXXXXX-XX \"");
        } else {
            txtLlave.setBorder(BorderFactory.createLineBorder(Color.green, 1));
            lbLlave.setText("Formato correcto");
        }
    }//GEN-LAST:event_txtLlaveFocusLost

    private void salir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salir1MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuGerente().setVisible(true);
            }
        });
        this.setVisible(false);
        this.dispose();
        parametros.close();
    }//GEN-LAST:event_salir1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parametrosFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parametrosFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parametrosFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parametrosFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parametrosFactura().setVisible(true);
            }
        });

    }

    private void insertarImagen(JLabel lbl, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(),
                        lbl.getHeight(),
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbFechaFinal;
    private javax.swing.JLabel lbFechaInicio;
    private javax.swing.JLabel lbIdParametro;
    private javax.swing.JLabel lbLlave;
    private javax.swing.JLabel lbValor;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel salir1;
    private javax.swing.JLabel tituloPantalla;
    private javax.swing.JTextField txtFechaFinal;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtIdParametro;
    private javax.swing.JTextField txtLlave;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
