/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.GUI;

import com.mycompany.sistemabarberia.JPACOntrollers.clientesJpaController;
import com.mycompany.sistemabarberia.JPACOntrollers.serviciosJpaController;
import com.mycompany.sistemabarberia.JPACOntrollers.tipodocumentoJpaController;
import com.mycompany.sistemabarberia.JTextFieldLimit;
import com.mycompany.sistemabarberia.Validaciones;
import com.mycompany.sistemabarberia.clientes;
import com.mycompany.sistemabarberia.servicios;
import com.mycompany.sistemabarberia.tipodocumento;
import java.awt.Color;
import java.awt.Image;
import java.sql.Date;
import java.text.ParseException;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author flore
 */
public class registrarClientes extends javax.swing.JFrame {
    
    private clientesJpaController clientesDAO = new clientesJpaController();
    private tipodocumentoJpaController tipodocumentoDAO = new tipodocumentoJpaController();
    private List<tipodocumento> documentosBD = tipodocumentoDAO.findtipodocumentoEntities();
    private serviciosJpaController serviciosDAO = new serviciosJpaController();
    private List<servicios> serviciosBD = serviciosDAO.findserviciosEntities();
    private java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
    private Validaciones validar = new Validaciones();
    private ImageIcon imagen;
    private Icon icono;
    Border redBorder = BorderFactory.createLineBorder(Color.RED,1);
    Border greenBorder = BorderFactory.createLineBorder(Color.GREEN,1);
    Border defaultBorder = new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true);

    /**
     * Creates new form registrarClientes
     */
    public registrarClientes() {
        initComponents();
       this.insertarImagen(this.logo,"src/main/resources/Imagenes/logoBarberia.png");
       
       Reiniciar();
        for(int i = 0; i < documentosBD.size(); i++)
        {
            tipoidDocumento.addItem(documentosBD.get(i).toString());
        }
        for(int i = 0; i < serviciosBD.size(); i++)
        {
            servicioProducto.addItem(serviciosBD.get(i).toString());
        }
        
    }
    
    public void Reiniciar()
    {
        formatoInvalidoNombre.setText(" ");
        formatoInvalidoApellido.setText(" ");
        formatoInvalidoTelefono.setText(" ");
        formatoInvalidoFechaNac.setText(" ");
        formatoInvalidoIdDocumento.setText(" ");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloPantalla = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        nombreCliente = new javax.swing.JTextField();
        telefonoCliente = new javax.swing.JTextField();
        fechaNacimiento = new javax.swing.JTextField();
        apellidosCliente = new javax.swing.JTextField();
        numeroidDocumento = new javax.swing.JTextField();
        servicioProducto = new javax.swing.JComboBox<>();
        tipoidDocumento = new javax.swing.JComboBox<>();
        formatoInvalidoNombre = new javax.swing.JLabel();
        formatoInvalidoApellido = new javax.swing.JLabel();
        formatoInvalidoTelefono = new javax.swing.JLabel();
        formatoInvalidoFechaNac = new javax.swing.JLabel();
        formatoInvalidoIdDocumento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        datosPersonales = new javax.swing.JLabel();
        crearPerfil = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 17, 17));

        tituloPantalla.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        tituloPantalla.setForeground(new java.awt.Color(255, 255, 255));
        tituloPantalla.setText("REGISTRAR PERFIL DEl CLIENTE");
        tituloPantalla.setMaximumSize(new java.awt.Dimension(364, 32));
        tituloPantalla.setMinimumSize(new java.awt.Dimension(364, 32));
        tituloPantalla.setPreferredSize(new java.awt.Dimension(364, 32));

        Cancelar.setBackground(new java.awt.Color(189, 158, 76));
        Cancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.setPreferredSize(new java.awt.Dimension(135, 31));
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(55, 53, 53));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(820, 329));

        jPanel3.setBackground(new java.awt.Color(55, 53, 53));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(794, 301));

        nombreCliente.setBackground(new java.awt.Color(30, 33, 34));
        nombreCliente.setDocument(new JTextFieldLimit(25));
        nombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        nombreCliente.setText("Nombres");
        nombreCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        nombreCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreClienteFocusLost(evt);
            }
        });
        nombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreClienteActionPerformed(evt);
            }
        });

        telefonoCliente.setBackground(new java.awt.Color(30, 33, 34));
        telefonoCliente.setDocument(new JTextFieldLimit(8));
        telefonoCliente.setForeground(new java.awt.Color(255, 255, 255));
        telefonoCliente.setText("Teléfono");
        telefonoCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        telefonoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefonoClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefonoClienteFocusLost(evt);
            }
        });
        telefonoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefonoClienteMouseClicked(evt);
            }
        });
        telefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoClienteActionPerformed(evt);
            }
        });

        fechaNacimiento.setBackground(new java.awt.Color(30, 33, 34));
        fechaNacimiento.setDocument(new JTextFieldLimit(25));
        fechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        fechaNacimiento.setText("Fecha de Nacimiento");
        fechaNacimiento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fechaNacimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fechaNacimientoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fechaNacimientoFocusLost(evt);
            }
        });
        fechaNacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechaNacimientoMouseClicked(evt);
            }
        });
        fechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaNacimientoActionPerformed(evt);
            }
        });

        apellidosCliente.setBackground(new java.awt.Color(30, 33, 34));
        apellidosCliente.setDocument(new JTextFieldLimit(25));
        apellidosCliente.setForeground(new java.awt.Color(255, 255, 255));
        apellidosCliente.setText("Apellidos");
        apellidosCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        apellidosCliente.setPreferredSize(new java.awt.Dimension(296, 42));
        apellidosCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apellidosClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                apellidosClienteFocusLost(evt);
            }
        });
        apellidosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosClienteActionPerformed(evt);
            }
        });

        numeroidDocumento.setBackground(new java.awt.Color(30, 33, 34));
        numeroidDocumento.setForeground(new java.awt.Color(255, 255, 255));
        numeroidDocumento.setText("Numero de Documento");
        numeroidDocumento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        numeroidDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numeroidDocumentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroidDocumentoFocusLost(evt);
            }
        });
        numeroidDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroidDocumentoActionPerformed(evt);
            }
        });

        servicioProducto.setBackground(new java.awt.Color(30, 33, 34));

        tipoidDocumento.setBackground(new java.awt.Color(30, 33, 34));

        formatoInvalidoNombre.setForeground(new java.awt.Color(255, 255, 255));
        formatoInvalidoNombre.setText("Formato invalido.");

        formatoInvalidoApellido.setForeground(new java.awt.Color(255, 255, 255));
        formatoInvalidoApellido.setText("Formato invalido.");

        formatoInvalidoTelefono.setForeground(new java.awt.Color(255, 255, 255));
        formatoInvalidoTelefono.setText("Formato invalido.");

        formatoInvalidoFechaNac.setForeground(new java.awt.Color(255, 255, 255));
        formatoInvalidoFechaNac.setText("Formato invalido.");

        formatoInvalidoIdDocumento.setForeground(new java.awt.Color(255, 255, 255));
        formatoInvalidoIdDocumento.setText("Formato invalido.");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Servicio:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                        .addComponent(telefonoCliente))
                    .addComponent(formatoInvalidoNombre)
                    .addComponent(formatoInvalidoTelefono)
                    .addComponent(formatoInvalidoFechaNac))
                .addGap(174, 174, 174)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(formatoInvalidoIdDocumento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(servicioProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apellidosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(tipoidDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(numeroidDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(47, 47, 47))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(formatoInvalidoApellido)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formatoInvalidoNombre)
                    .addComponent(formatoInvalidoApellido))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroidDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoidDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formatoInvalidoTelefono)
                    .addComponent(formatoInvalidoIdDocumento))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servicioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formatoInvalidoFechaNac)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        datosPersonales.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        datosPersonales.setForeground(new java.awt.Color(255, 255, 255));
        datosPersonales.setText("DATOS PERSONALES DEL CLIENTE:");

        crearPerfil.setBackground(new java.awt.Color(189, 158, 76));
        crearPerfil.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        crearPerfil.setText("Crear Perfil");
        crearPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPerfilActionPerformed(evt);
            }
        });

        logo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(tituloPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datosPersonales)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(crearPerfil)
                        .addGap(182, 182, 182)
                        .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tituloPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(datosPersonales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoClienteActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_telefonoClienteActionPerformed

    private void fechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaNacimientoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fechaNacimientoActionPerformed

    private void nombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreClienteActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_nombreClienteActionPerformed

    private void apellidosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosClienteActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_apellidosClienteActionPerformed

    private void fechaNacimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaNacimientoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fechaNacimientoMouseClicked

    private void crearPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPerfilActionPerformed
        // TODO add your handling code here:
        
        java.util.Date birthDate;
        String fechaNac = "00-00-0000";
        try {
        birthDate = sdf.parse(convertirFecha(fechaNacimiento.getText()));
        fechaNac = sdf.format(birthDate);
    } catch (ParseException ex) {
       ex.printStackTrace();
    }
        clientes registrarClientes = new clientes();
        registrarClientes.setNomCliente(nombreCliente.getText());
        registrarClientes.setApeCliente(apellidosCliente.getText());
        registrarClientes.setNumTelefono(telefonoCliente.getText());
        registrarClientes.setNumDocumento(Integer.parseInt(numeroidDocumento.getText()));
        registrarClientes.setIDTipoDocumento(Integer.parseInt(tipoidDocumento.getSelectedItem().toString()));
        registrarClientes.setIDServicio(Integer.parseInt(servicioProducto.getSelectedItem().toString()));
        registrarClientes.setFechaNacimiento(Date.valueOf(fechaNac));
        registrarClientes.setActivo(true);
        

        if(validarNombre() && validarApellido() &&  validarCamposNumero(telefonoCliente,formatoInvalidoTelefono) &&
           validarFecha(fechaNacimiento,formatoInvalidoFechaNac))
        {   
            try {
            clientesDAO.create(registrarClientes); 
            JOptionPane.showMessageDialog(null,"Operación Exitosa.");
                    Reiniciar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"No se pudo guardar el cliente, excepción: " + ex.getMessage());
        }
        }else{ JOptionPane.showMessageDialog(null,"Por favor, introduzca datos válidos.");}
    }//GEN-LAST:event_crearPerfilActionPerformed

    private void numeroidDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroidDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroidDocumentoActionPerformed

    private void nombreClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreClienteFocusLost
        if(nombreCliente.getText().equals(""))
        {
            nombreCliente.setText("Nombres");
        }else
        {
        validarNombre();   
        }
    }//GEN-LAST:event_nombreClienteFocusLost

    private void apellidosClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellidosClienteFocusLost
        // TODO add your handling code here:
        if(apellidosCliente.getText().equals(""))
        {
            apellidosCliente.setText("Apellidos");
        }else
        {
        validarApellido();    
        }
    }//GEN-LAST:event_apellidosClienteFocusLost

    private void nombreClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreClienteFocusGained
        // TODO add your handling code here:
        if(nombreCliente.getText().equals("Nombres"))
        {
            nombreCliente.setText("");
        }
    }//GEN-LAST:event_nombreClienteFocusGained

    private void apellidosClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellidosClienteFocusGained
        // TODO add your handling code here:
        if(apellidosCliente.getText().equals("Apellidos"))
        {
            apellidosCliente.setText("");
        }
    }//GEN-LAST:event_apellidosClienteFocusGained

    private void telefonoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoClienteFocusLost
        // TODO add your handling code here:
         if(telefonoCliente.getText().equals(""))
        {
            telefonoCliente.setText("Teléfono");
        }else
        {
            validarCamposNumero();
        }
    }//GEN-LAST:event_telefonoClienteFocusLost

    private void fechaNacimientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechaNacimientoFocusLost
        // TODO add your handling code here:
        if(fechaNacimiento.getText().equals(""))
        {
            fechaNacimiento.setText("Fecha de Nacimiento");
        }else
        {
         validarFecha(fechaNacimiento,formatoInvalidoFechaNac);   
        }
    }//GEN-LAST:event_fechaNacimientoFocusLost

    private void fechaNacimientoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechaNacimientoFocusGained
        // TODO add your handling code here:
        if(fechaNacimiento.getText().equals("Fecha de Nacimiento"))
        {
            fechaNacimiento.setText("");
            fechaNacimiento.setDocument(new JTextFieldLimit(10));
        }
        
    }//GEN-LAST:event_fechaNacimientoFocusGained

    private void numeroidDocumentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroidDocumentoFocusGained
        // TODO add your handling code here:
        if(numeroidDocumento.getText().equals("Numero de Documento"))
        {
            numeroidDocumento.setDocument(new JTextFieldLimit(13));
            numeroidDocumento.setText("");
        }
    }//GEN-LAST:event_numeroidDocumentoFocusGained

    private void numeroidDocumentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroidDocumentoFocusLost
        // TODO add your handling code here:
        if(numeroidDocumento.getText().equals(""))
        {
            numeroidDocumento.setText("Numero de Documento");
        }else
        {
            
        }
        
    }//GEN-LAST:event_numeroidDocumentoFocusLost

    private void telefonoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefonoClienteMouseClicked
        // TODO add your handling code here:
        telefonoCliente.setDocument(new JTextFieldLimit(8));
    }//GEN-LAST:event_telefonoClienteMouseClicked

    private void telefonoClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefonoClienteFocusGained
        // TODO add your handling code here:
        if(telefonoCliente.getText().equals("Teléfono"))
        {
            telefonoCliente.setText("");
        }
        
    }//GEN-LAST:event_telefonoClienteFocusGained

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarClientes().setVisible(true);
            }
        });
        
        
    }
    
    private void insertarImagen(JLabel lbl,String ruta)
    {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(), 
                        lbl.getHeight(),
                        Image.SCALE_DEFAULT)
        );
        lbl.setIcon(this.icono);
        this.repaint();
    }
    
    private void validarCamposNumero()
    {
        if(!validar.validacionFecha(telefonoCliente.getText()))
            {
            telefonoCliente.setBorder(redBorder);
            formatoInvalidoTelefono.setVisible(true);
            formatoInvalidoTelefono.setText("El numero de tel debe contener 8 digitos");
            return;
            }else
        {
            telefonoCliente.setBorder(greenBorder);
            formatoInvalidoTelefono.setText("");
        }
    }
    
    private boolean validarFecha(javax.swing.JTextField fecha, JLabel label)
    {
        if(!validar.validacionFormatoFecha(fecha.getText()) )
        {
            fecha.setBorder(redBorder);
            label.setVisible(true);
            label.setText("El formato de fecha es: dd/mm/aaaa");
            return false;
        }
        if(!validar.validacionFecha(fecha.getText()))
            {
            fecha.setBorder(redBorder);
            label.setVisible(true);
            label.setText("La fecha introducida es inválida.");
            return false;
            }else
        {
            fecha.setBorder(greenBorder);
            label.setText(" ");
            return true;
        }
    }
    
     private boolean validarApellido()
    {
        if(!validar.validacionCantidadMinima(apellidosCliente.getText(),6))
            {
            apellidosCliente.setBorder(redBorder);
            formatoInvalidoApellido.setVisible(true);
            formatoInvalidoApellido.setText("El apellido debe ser de minimo 6 letras.");
            return false;
            }
        if (!validar.validacionNombres(apellidosCliente.getText()))
        {
            apellidosCliente.setBorder(redBorder);
            formatoInvalidoApellido.setVisible(true);
            formatoInvalidoApellido.setText("Cada apellido debe empezar en mayuscula.");
            return false;
        }
        if(validar.validacionCadenaPalabras(apellidosCliente.getText()))
        {    
            apellidosCliente.setBorder(greenBorder);
            formatoInvalidoApellido.setVisible(true);
            formatoInvalidoApellido.setText("Formato válido");
            return true;
            
        }else
        {
            apellidosCliente.setBorder(redBorder);
            formatoInvalidoApellido.setVisible(true);
            formatoInvalidoApellido.setText("No puedes repetir letras.");
            return false;
        }
     
    }
     
     private boolean validarNombre()
    {
        if(!validar.validacionCantidadMinima(nombreCliente.getText(),6))
            {
            nombreCliente.setBorder(redBorder);
            formatoInvalidoNombre.setVisible(true);
            formatoInvalidoNombre.setText("El nombre debe ser de minimo 6 letras.");
            return false;
            }
        if (!validar.validacionNombres(nombreCliente.getText()))
        {
            nombreCliente.setBorder(redBorder);
            formatoInvalidoNombre.setVisible(true);
            formatoInvalidoNombre.setText("Cada nombre debe empezar en mayuscula.");
            return false;
        }
        if(validar.validacionCadenaPalabras(nombreCliente.getText()))
        {    
            nombreCliente.setBorder(greenBorder);
            formatoInvalidoNombre.setVisible(true);
            formatoInvalidoNombre.setText("Formato válido");
            return true;
            
        }else
        {
            nombreCliente.setBorder(redBorder);
            formatoInvalidoNombre.setVisible(true);
            formatoInvalidoNombre.setText("No puedes repetir letras.");
            return false;
        }
    }
     
   private boolean validarCamposNumero(javax.swing.JTextField telefonoEmpleado,JLabel formatoInvalidoTelefono)
    {
        if(!validar.validacionCampoNumerico(telefonoEmpleado.getText()))
        {
            telefonoEmpleado.setBorder(redBorder);
            formatoInvalidoTelefono.setVisible(true);
            formatoInvalidoTelefono.setText("Solo puedes ingresar numeros en este campo.");
            return false;
        }
        if(!validar.validarNumCelular(telefonoEmpleado.getText()))
            {
            telefonoEmpleado.setBorder(redBorder);
            formatoInvalidoTelefono.setVisible(true);
            formatoInvalidoTelefono.setText("El numero de teléfono es inválido.");
            return false;
            }else
        {
            telefonoEmpleado.setBorder(greenBorder);
            formatoInvalidoTelefono.setText(" ");
            return true;
        }
    }
   
     private String convertirFecha(String Fecha)
    {
        String[] palabras  = Fecha.split("/");
       
        return palabras[2] + "-" + palabras[1] + "-" + palabras[0];
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField apellidosCliente;
    private javax.swing.JButton crearPerfil;
    private javax.swing.JLabel datosPersonales;
    private javax.swing.JTextField fechaNacimiento;
    private javax.swing.JLabel formatoInvalidoApellido;
    private javax.swing.JLabel formatoInvalidoFechaNac;
    private javax.swing.JLabel formatoInvalidoIdDocumento;
    private javax.swing.JLabel formatoInvalidoNombre;
    private javax.swing.JLabel formatoInvalidoTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JTextField numeroidDocumento;
    private javax.swing.JComboBox<String> servicioProducto;
    private javax.swing.JTextField telefonoCliente;
    private javax.swing.JComboBox<String> tipoidDocumento;
    private javax.swing.JLabel tituloPantalla;
    // End of variables declaration//GEN-END:variables
}
